### ISSUE TITLE
Implement python nose coverage provider

### ISSUE THREAD

**Issue by dbarnett** [google/vim-coverage#8]
Add a coverage provider to support reading python coverage results from "nosetests --with-coverage" into vim.

**Comment by blueyed** [comment]
Does this generate coverage.py reports?
https://github.com/alfredodeza/coveragepy.vim could be extended to act as a provider then maybe.

**Comment by dbarnett** [comment]
Possibly. Looks like that might just be its own self-contained alternative and as much work to adapt that as to plug into nosetests directly, but I could be wrong… only glanced at it.
